DROP TABLE COUPON CASCADE CONSTRAINTS;	

CREATE TABLE COUPON (
	COUPON_NUM NUMBER PRIMARY KEY,
	COUPON_CODE VARCHAR2(30),
    	COUPON_TYPE VARCHAR2(30),
    	COUPON_VALUE NUMBER,
    	COUPON_EX VARCHAR2(30)
);

INSERT INTO COUPON(COUPON_NUM, COUPON_CODE, COUPON_TYPE, COUPON_VALUE)
VALUES (101, 'ACE135', 'ticket', 15000);

