DROP TABLE COUPON CASCADE CONSTRAINTS;	

CREATE TABLE COUPON (
    COUPON_NUM NUMBER PRIMARY KEY,
    COUPON_CODE VARCHAR2(50),
    COUPON_TYPE VARCHAR2(30),
    COUPON_VALUE NUMBER,
    COUPON_EX VARCHAR2(30),
    PAY_NUM NUMBER,
    FOREIGN KEY (PAY_NUM) REFERENCES STORE_PAY(PAY_NUM) ON DELETE CASCADE
);

ALTER TABLE COUPON
MODIFY COUPON_CODE VARCHAR2(50);

ALTER TABLE COUPON
ADD CONSTRAINT UQ_PAY_NUM UNIQUE (PAY_NUM);

INSERT INTO COUPON(COUPON_NUM, COUPON_CODE, COUPON_TYPE, COUPON_VALUE)
VALUES (101, 'ACE135', 'ticket', 15000);
INSERT INTO COUPON(COUPON_NUM, COUPON_CODE, COUPON_TYPE, COUPON_VALUE)
VALUES (102, '123', 'ticket', 15000);

select * from COUPON
		where COUPON_CODE = '123';