CREATE TABLE EVENT_APPLY (
	EVENT_NUM NUMBER,							--이벤트 번호
 	MEMBER_ID VARCHAR2(100),					--회원 아이디
	EVENT_DRAW VARCHRA2(30)						--당첨 여부
	
 	FOREIGN KEY (EVENT_NUM) REFERENCES EVENT(EVENT_NUM) ON DELETE CASCADE
);

