--이벤트 테이블
create table EVENT(
	EVENT_NUM			NUMBER		  PRIMARY KEY,	--이벤트 글 번호
	EVENT_TYPE			VARCHAR2(30)  NOT NULL,		--이벤트 종류
	EVENT_SUBJECT			VARCHAR2(200) NOT NULL,		--이벤트 제목
	EVENT_CONTENT			VARCHAR2(300),				--이벤트 내용
	EVENT_DATE			DATE 		  NOT NULL,		--작성일자
	EVENT_FILE			VARCHAR2(300),				--이벤트 업로드 파일
	EVENT_STARTDATE			VARCHAR2(20) NOT NULL,		-- 이벤트 시작일
	EVENT_ENDDATE			VARCHAR2(20) NOT NULL,		-- 이벤트 종료일
	EVENT_STATUS			VARCHAR2(20),				-- 이벤트 상태(대기/진행중/종료)
	EVENT_RESULTDATE		VARCHAR2(20),
	EVENT_RESULT			VARCHAR2(4000)
);

