CREATE SEQUENCE FAVORITE_THEATER_SEQ;

CREATE TABLE FAVORITE_THEATER (
 	FAVORITE_THEATER_ID NUMBER PRIMARY KEY,
 	MEMBER_NUM NUMBER,
 	THEATER_ID NUMBER,
	FOREIGN KEY (MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM) ON DELETE CASCADE,
	FOREIGN KEY (THEATER_ID) REFERENCES THEATER(THEATER_ID) ON DELETE CASCADE
);