DROP TABLE KAKAO_PAY CASCADE CONSTRAINTS;	

CREATE TABLE KAKAO_PAY (
	KPAY_NUM NUMBER PRIMARY KEY,
	THEATER_SCHEDULE_ID NUMBER,
    	KPAY_AMOUNT NUMBER,
	KAPY_OCCUPIED_SEAT VARCHAR(50),
	KPAY_SEAT_CNT NUMBER,
	MEMBER_ID VARCHAR2(20),
	pg_token VARCHAR(50),
	FOREIGN KEY (THEATER_SCHEDULE_ID) REFERENCES THEATER_SCHEDULE(THEATER_SCHEDULE_ID) ON DELETE CASCADE,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE -- 상영관 등 추가하기
);


insert into STORE_PAY(PAY_NUM, PAY_APPROVED)
values(100, 'n')	

INSERT INTO STORE_PAY(PAY_NUM, PAY_APPROVED)
VALUES (101, 'n');


SELECT STORE_PAY.*, STORE_ITEM.ITEM_NAME, STORE_ITEM.ITEM_PRICE 
FROM STORE_CART
INNER JOIN STORE_ITEM ON STORE_CART.ITEM_CODE = STORE_ITEM.ITEM_CODE
WHERE STORE_CART.ITEM_CODE = '301';

SELECT *
FROM STORE_PAY
INNER JOIN STORE_ITEM ON STORE_CART.ITEM_CODE = STORE_ITEM.ITEM_CODE
WHERE STORE_CART.ITEM_CODE = '301';

success 페이지 만들기