CREATE TABLE MOVIE_REVIEW (
  MOVIE_REVIEW_NUM NUMBER,
  MEMBER_ID VARCHAR2(20),
  MOVIE_REVIEW_STAR NUMBER,
  MOVIE_REVIEW_COMMENT VARCHAR2(100),
  MOVIE_CODE VARCHAR2(20),
  MOVIE_REVIEW_REG_DATE DATE,
  MOVIE_REVIEW_LIKE NUMBER,
  CONSTRAINT PK_MOVIE_REVIEW PRIMARY KEY (MOVIE_REVIEW_NUM),
  CONSTRAINT FK_MOVIE_REVIEW_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT FK_MOVIE_REVIEW_MOVIE FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE)
);

CREATE SEQUENCE MOVIE_REVIEW_SEQ;