CREATE TABLE MOVIEPOST_DIBS (
  MOVIEPOST_DIBS_ID NUMBER,
  MEMBER_ID VARCHAR2(20),
  MOVIEPOST_DIBS_OBJECT VARCHAR2(20),
  CONSTRAINT PK_MOVIEPOST_DIBS PRIMARY KEY (MOVIEPOST_DIBS_ID),
  CONSTRAINT FK_MOVIEPOST_DIBS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE SEQUENCE MOVIEPOST_DIBS_SEQ;