CREATE TABLE MOVIEPOST (
  MOVIEPOST_NUM NUMBER,
  MOVIE_CODE VARCHAR2(10),
  MEMBER_ID VARCHAR2(20),
  MOVIEPOST_STILL VARCHAR2(4000),
  MOVIEPOST_CONTENT CLOB,
  MOVIEPOST_REG_DATE DATE,
  CONSTRAINT PK_MOVIEPOST PRIMARY KEY (MOVIEPOST_NUM),
  CONSTRAINT FK_MOVIEPOST_MOVIE FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE)
);

CREATE SEQUENCE MOVIEPOST_SEQ;