CREATE TABLE MOVIEPOST_COMMENT (
  MOVIEPOST_COMMENT_NUM NUMBER,
  MEMBER_ID VARCHAR2(20),
  MOVIEPOST_NUM NUMBER,
  MOVIEPOST_COMMENT_CONTENT VARCHAR2(200), 
  CONSTRAINT PK_MOVIEPOST_COMMENT PRIMARY KEY (MOVIEPOST_COMMENT_NUM),
  CONSTRAINT FK_MOVIEPOST_COMMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT FK_MOVIEPOST_NUM FOREIGN KEY (MOVIEPOST_NUM) REFERENCES MOVIEPOST(MOVIEPOST_NUM) ON DELETE CASCADE
);

CREATE SEQUENCE MOVIEPOST_COMMENT_SEQ;