CREATE TABLE MOVIEPOST_COMMENT (
 	MOVIEPOST_COMMENT_NUM NUMBER PRIMARY KEY,
 	MEMBER_ID VARCHAR2(100),
	MOVIEPOST_NUM NUMBER,
 	MOVIEPOST_COMMENT_CONTENT VARCHAR2(3000),
 	MOVIEPOST_COMMENT_DATE VARCHAR2(300),
 	FOREIGN KEY (MOVIEPOST_NUM) REFERENCES MOVIEPOST(MOVIEPOST_NUM) ON DELETE CASCADE
);

CREATE SEQUENCE MOVIEPOST_COMMENT_SEQ;