-- 예매율 계산 쿼리

WITH totalseatcount AS(
 SELECT SUM(KPAY_SEAT_CNT) as totalseat
 FROM kakao_pay
 INNER JOIN THEATER_SCHEDULE
 ON kakao_pay.THEATER_SCHEDULE_ID = THEATER_SCHEDULE.THEATER_SCHEDULE_ID
 INNER JOIN MOVIE
 ON THEATER_SCHEDULE.MOVIE_CODE = MOVIE.MOVIE_CODE
 WHERE kakao_pay.pg_token IS NOT NULL
 and THEATER_SCHEDULE_DATE = '2023-10-24'
),
movieseatcount AS(
 SELECT SUM(KPAY_SEAT_CNT) as movieseat, MOVIE.MOVIE_CODE, MOVIE.MOVIE_TITLE
 FROM kakao_pay
 INNER JOIN THEATER_SCHEDULE
 ON kakao_pay.THEATER_SCHEDULE_ID = THEATER_SCHEDULE.THEATER_SCHEDULE_ID
 INNER JOIN MOVIE
 ON THEATER_SCHEDULE.MOVIE_CODE = MOVIE.MOVIE_CODE
 WHERE kakao_pay.pg_token IS NOT NULL
 AND THEATER_SCHEDULE_DATE = '2023-10-24'
 AND MOVIE.MOVIE_CODE = '20219997'
 GROUP BY MOVIE.MOVIE_CODE, MOVIE.MOVIE_TITLE
)
select (movieseatcount.movieseat / totalseatcount.totalseat) * 100 AS ratio, movieseatcount.MOVIE_CODE, movieseatcount.MOVIE_TITLE
from totalseatcount, movieseatcount

