DROP TABLE STORE_ITEM CASCADE CONSTRAINTS;	

CREATE TABLE STORE_ITEM (
	ITEM_CODE NUMBER PRIMARY KEY,
    	ITEM_NAME VARCHAR2(20),
    	ITEM_PRICE NUMBER,
    	ITEM_DETAIL VARCHAR2(2000),
    	ITEM_FILE varchar2(50),-- 첨부될 파일명(가공)
  	ITEM_ORIGINAL  varchar2(50) -- 첨부 파일명
);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_NAME, ITEM_PRICE)
VALUES (1, 'popcorn', 5000);
INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_NAME, ITEM_PRICE)
VALUES (2, 'test1', 7777);
