DROP TABLE STORE_CART CASCADE CONSTRAINTS;	


CREATE TABLE STORE_CART (
    	CART_NUM NUMBER PRIMARY KEY,
    	ITEM_CODE NUMBER,
    	MEMBER_ID VARCHAR2(20),
	ITEM_CNT NUMBER,
    	FOREIGN KEY (ITEM_CODE) REFERENCES STORE_ITEM(ITEM_CODE) ON DELETE CASCADE,
    	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);



insert into STORE_CART(CART_NUM, CART_APPROVED)
values(100, 'n')	

INSERT INTO STORE_ITEM(CART_NUM, CART_APPROVED)
VALUES (101, 'n');


SELECT STORE_CART.*, STORE_ITEM.ITEM_NAME, STORE_ITEM.ITEM_PRICE 
FROM STORE_CART
INNER JOIN STORE_ITEM ON STORE_CART.ITEM_CODE = STORE_ITEM.ITEM_CODE
WHERE STORE_CART.ITEM_CODE = '301';

SELECT *
FROM STORE_CART
INNER JOIN STORE_ITEM ON STORE_CART.ITEM_CODE = STORE_ITEM.ITEM_CODE
WHERE STORE_CART.ITEM_CODE = '301';