DROP TABLE STORE_ITEM CASCADE CONSTRAINTS;	

CREATE TABLE STORE_ITEM (
	ITEM_CODE NUMBER PRIMARY KEY,
	ITEM_MENU VARCHAR2(20),
    	ITEM_NAME VARCHAR2(20),
    	ITEM_PRICE NUMBER,
    	ITEM_DETAIL VARCHAR2(2000),
    	ITEM_FILE varchar2(50),-- 첨부될 파일명(가공)
  	ITEM_ORIGINAL  varchar2(50) -- 첨부 파일명
);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (101, 'ticket','noraml2D', 5000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (102, 'ticket','3D', 6000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (201, 'snack','sprite', 2500);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (202, 'snack','popcorn', 4500);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (203, 'snack','nacho', 3500);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (301, 'voucher','5000v', 5000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (302, 'voucher','10000v', 10000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (303, 'voucher','15000v', 15000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (401, 'point','30000p', 30000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (402, 'point','10000p', 20000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (403, 'point','10000p', 10000);

INSERT INTO STORE_ITEM(ITEM_CODE, ITEM_MENU, ITEM_NAME, ITEM_PRICE)
VALUES (404, 'point','5000p', 5000);

