CREATE SEQUENCE THEATER_SCHEDULE_SEQ;

CREATE TABLE THEATER_SCHEDULE(
 	THEATER_SCHEDULE_ID NUMBER PRIMARY KEY,
	THEATER_ROOM_ID NUMBER NOT NULL,
 	THEATER_SCHEDULE_STARTTIME VARCHAR2(200) NOT NULL,
	THEATER_SCHEDULE_DATE VARCHAR2(200) NOT NULL,
	MOVIE_CODE NUMBER NOT NULL,
	THEATER_SCHEDULE_TYPE VARCHAR2(100),
 	FOREIGN KEY (THEATER_ROOM_ID) REFERENCES THEATER_ROOM(THEATER_ROOM_ID) ON DELETE CASCADE
	);


INSERT INTO THEATER_SCHEDULE VALUES (THEATER_SCHEDULE_SEQ.NEXTVAL, 22, '1', '12:00', 1, '조조');

INSERT INTO THEATER_SCHEDULE VALUES (THEATER_SCHEDULE_SEQ.NEXTVAL, 23, '1', '12:00', 1, '조조');
INSERT INTO THEATER_SCHEDULE VALUES (THEATER_SCHEDULE_SEQ.NEXTVAL, 23, '14:00',2023-10-05', 1, '조조');


SELECT THEATER_ROOM_ID
FROM THEATER_ROOM
WHERE THEATER_ID = #{THEATER_ID}

SELECT *
FROM THEATER_SCHEDULE
WHERE THEATER_ID IN ( SELECT THEATER_ROOM_ID
			FROM THEATER_ROOM
			WHERE THEATER_ID = #{THEATER_ID} )



		SELECT *
		FROM THEATER_SCHEDULE
		WHERE THEATER_ROOM_ID IN ( SELECT THEATER_ROOM_ID
									FROM THEATER_ROOM
									WHERE THEATER_ID = 23 )
		AND THEATER_SCHEDULE_DATE = '2023-10-05'


		SELECT *
		FROM THEATER_SCHEDULE
		WHERE THEATER_SCHEDULE_DATE = '2023-10-05'