CREATE SEQUENCE THEATER_SCHEDULE_SEQ;

CREATE TABLE THEATER_SCHEDULE(
 	THEATER_SCHEDULE_ID NUMBER PRIMARY KEY,
	THEATER_ID NUMBER NOT NULL,
	THEATER_ROOM_ID NUMBER NOT NULL,
 	THEATER_SCHEDULE_STARTTIME VARCHAR2(200) NOT NULL,
	THEATER_SCHEDULE_DATE VARCHAR2(200) NOT NULL,
	MOVIE_CODE NUMBER NOT NULL,
	THEATER_SCHEDULE_TYPE VARCHAR2(100),
 	FOREIGN KEY (THEATER_ROOM_ID) REFERENCES THEATER_ROOM(THEATER_ROOM_ID) ON DELETE CASCADE,
	FOREIGN KEY (THEATER_ID) REFERENCES THEATER(THEATER_ID) ON DELETE CASCADE
	);


INSERT INTO THEATER_SCHEDULE VALUES (THEATER_SCHEDULE_SEQ.NEXTVAL, 113, 23, '14:00', '2023-10-06', 1, '조조');

