package com.hta.movieplus.domain;

public class NoticeVO {
	private int CUSTOMER_NOTICE_NUM; // 공지글 번호
	private String CUSTOMER_NOTICE_TYPE; // 전체/ 극장별 공지 선택
	private String CUSTOMER_NOTICE_REGION; // 지역명
	private String CUSTOMER_NOTICE_THEATER; // 극장 선택
	private String CUSTOMER_NOTICE_SUBJECT; // 제목
	private String CUSTOMER_NOTICE_CONTENT; // 내용
	private String CUSTOMER_NOTICE_SYSDATE; // 등록일
	
	private int RNUM;
	
	public int getCUSTOMER_NOTICE_NUM() {
		return CUSTOMER_NOTICE_NUM;
	}
	public void setCUSTOMER_NOTICE_NUM(int cUSTOMER_NOTICE_NUM) {
		CUSTOMER_NOTICE_NUM = cUSTOMER_NOTICE_NUM;
	}
	public String getCUSTOMER_NOTICE_TYPE() {
		return CUSTOMER_NOTICE_TYPE;
	}
	public void setCUSTOMER_NOTICE_TYPE(String cUSTOMER_NOTICE_TYPE) {
		CUSTOMER_NOTICE_TYPE = cUSTOMER_NOTICE_TYPE;
	}
	public String getCUSTOMER_NOTICE_REGION() {
		return CUSTOMER_NOTICE_REGION;
	}
	public void setCUSTOMER_NOTICE_REGION(String cUSTOMER_NOTICE_REGION) {
		CUSTOMER_NOTICE_REGION = cUSTOMER_NOTICE_REGION;
	}
	public String getCUSTOMER_NOTICE_THEATER() {
		return CUSTOMER_NOTICE_THEATER;
	}
	public void setCUSTOMER_NOTICE_THEATER(String cUSTOMER_NOTICE_THEATER) {
		CUSTOMER_NOTICE_THEATER = cUSTOMER_NOTICE_THEATER;
	}
	public String getCUSTOMER_NOTICE_SUBJECT() {
		return CUSTOMER_NOTICE_SUBJECT;
	}
	public void setCUSTOMER_NOTICE_SUBJECT(String cUSTOMER_NOTICE_SUBJECT) {
		CUSTOMER_NOTICE_SUBJECT = cUSTOMER_NOTICE_SUBJECT;
	}
	public String getCUSTOMER_NOTICE_CONTENT() {
		return CUSTOMER_NOTICE_CONTENT;
	}
	public void setCUSTOMER_NOTICE_CONTENT(String cUSTOMER_NOTICE_CONTENT) {
		CUSTOMER_NOTICE_CONTENT = cUSTOMER_NOTICE_CONTENT;
	}
	public String getCUSTOMER_NOTICE_SYSDATE() {
		return CUSTOMER_NOTICE_SYSDATE;
	}
	public void setCUSTOMER_NOTICE_SYSDATE(String cUSTOMER_NOTICE_SYSDATE) {
		CUSTOMER_NOTICE_SYSDATE = cUSTOMER_NOTICE_SYSDATE;
	}
	@Override
	public String toString() {
		return "NoticeVO [CUSTOMER_NOTICE_NUM=" + CUSTOMER_NOTICE_NUM + ", CUSTOMER_NOTICE_TYPE=" + CUSTOMER_NOTICE_TYPE
				+ ", CUSTOMER_NOTICE_REGION=" + CUSTOMER_NOTICE_REGION + ", CUSTOMER_NOTICE_THEATER="
				+ CUSTOMER_NOTICE_THEATER + ", CUSTOMER_NOTICE_SUBJECT=" + CUSTOMER_NOTICE_SUBJECT
				+ ", CUSTOMER_NOTICE_CONTENT=" + CUSTOMER_NOTICE_CONTENT + ", CUSTOMER_NOTICE_SYSDATE="
				+ CUSTOMER_NOTICE_SYSDATE + "]";
	}
	public int getRNUM() {
		return RNUM;
	}
	public void setRNUM(int rNUM) {
		RNUM = rNUM;
	}

	
}